name = "MixedComplementarityProblems"
uuid = "6c9e26cb-9263-41b8-a6c6-f4ca104ccdcd"
authors = ["David Fridovich-Keil <dfk@utexas.edu>"]
version = "0.1.6"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SymbolicTracingUtils = "77ddf47f-b2ab-4ded-95ee-54f4fa148129"
TrajectoryGamesBase = "ac1ac542-73eb-4349-ae1b-660ab3609574"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
BlockArrays = "0.16.43, 1"
ChainRulesCore = "1.25.0"
DataStructures = "0.18.20"
FiniteDiff = "2.26.2"
ForwardDiff = "0.10.38"
LinearAlgebra = "1.11.0"
LinearSolve = "2.38.0"
SciMLBase = "2.70.0"
SparseArrays = "1.11.0"
SymbolicTracingUtils = "0.1.1"
TrajectoryGamesBase = "0.3.10"
Zygote = "0.6.73"
julia = "1.11"
